### PR TITLE
Fix java.time encoders

### LINKED ISSUE #115: Quotes missing from java.time encoders
```
@ JsonDecoder[DayOfWeek].decodeJson(JsonEncoder[DayOfWeek].encodeJson(DayOfWeek.MONDAY, None))
res17: Either[String, DayOfWeek] = Left("(expected '\"' got 'M')")
```

### PR DESCRIPTION
**Pull request by steinybot**
Fixes #115

### CODE REVIEW

File: zio-json/jvm/src/test/scala/zio/json/JavaTimeSpec.scala [hunk 1]
```diff
@@ -11,118 +11,120 @@ import zio.{ test => _, _ }
 
 // zioJsonJVM/testOnly testzio.json.JavaTimeSpec
 object JavaTimeSpec extends DefaultRunnableSpec {
-  private def stringify(s: String): String = s""" "${s}" """
+  private def stringify(s: Any): String = s""" "${s.toString}" """
+
+  private def equalToStringified(expected: String) = equalTo(s""""$expected"""")
```
Comment (fsvehla) [inline zio-json/jvm/src/test/scala/zio/json/JavaTimeSpec.scala:16]: Nice :)
